CREATE DATABASE 1712267_QuanLySinhVien;
USE 1712267_QuanLySinhVien;

-- DROP DATABASE 1712267_QuanLySinhVien;


-- Tables
CREATE TABLE IF NOT EXISTS QUYEN(
	MA_QUYEN INT AUTO_INCREMENT,
    TEN_QUYEN NVARCHAR(20) NOT NULL UNIQUE,
    MIEU_TA NVARCHAR(40) NOT NULL,
    CONSTRAINT PK_QUYEN PRIMARY KEY (MA_QUYEN)
);

CREATE TABLE IF NOT EXISTS GIOITINH(
	MA_GIOITINH INT AUTO_INCREMENT,
    TEN_GIOITINH NVARCHAR(20) NOT NULL UNIQUE,
    CONSTRAINT PK_GIOITINH PRIMARY KEY (MA_GIOITINH)
);

CREATE TABLE IF NOT EXISTS LOP(
	LOP_NO INT AUTO_INCREMENT,
	MA_LOP NVARCHAR(8) NOT NULL UNIQUE,
    TEN_LOP NVARCHAR(40),
    MIEU_TA TEXT,
    CONSTRAINT PK_LOP PRIMARY KEY (LOP_NO)
);

CREATE TABLE IF NOT EXISTS SINHVIEN(
	SINHVIEN_NO INT AUTO_INCREMENT,
    
    MA_SINHVIEN VARCHAR(10) NOT NULL UNIQUE, -- Tên đăng nhập
    PASSWORD_SINHVIEN VARCHAR(100),
    
    TEN_SINHVIEN NVARCHAR(80) NOT NULL,
    CMND_SINHVIEN VARCHAR(10) NOT NULL UNIQUE,
    
    GIOITINH_SINHVIEN  NVARCHAR(20) NOT NULL,
    MALOP_SINHVIEN NVARCHAR(8) NOT NULL,
    MA_QUYEN INT NOT NULL DEFAULT (2),
    CONSTRAINT PK_SINHVIEN PRIMARY KEY (SINHVIEN_NO),
    CONSTRAINT FK_GIOITINH_SINHVIEN FOREIGN KEY (GIOITINH_SINHVIEN)
    REFERENCES GIOITINH(TEN_GIOITINH),
    CONSTRAINT FK_SINHVIEN_MALOP FOREIGN KEY (MALOP_SINHVIEN)
    REFERENCES LOP(MA_LOP),
    CONSTRAINT FK_SINHVIEN_QUYEN FOREIGN KEY (MA_QUYEN)
    REFERENCES QUYEN(MA_QUYEN)
);

CREATE TABLE IF NOT EXISTS GIAOVU(
	GIAOVU_NO INT AUTO_INCREMENT,
    
    MA_GIAOVU VARCHAR(10) NOT NULL UNIQUE,
    PASSWORD_GIAOVU VARCHAR(100),
    
    TEN_GIAOVU NVARCHAR(80) NOT NULL,
    CMND_GIAOVU VARCHAR(10) NOT NULL UNIQUE,
    
    GIOITINH_GIAOVU  NVARCHAR(20) NOT NULL,
    MA_QUYEN INT NOT NULL DEFAULT(1),
    CONSTRAINT PK_GIAOVU PRIMARY KEY (GIAOVU_NO),
    CONSTRAINT FK_GIOITINH_GIAOVU FOREIGN KEY (GIOITINH_GIAOVU)
    REFERENCES GIOITINH(TEN_GIOITINH),
    CONSTRAINT FK_GIAOVU_QUYEN FOREIGN KEY (MA_QUYEN)
    REFERENCES QUYEN(MA_QUYEN)
);

CREATE TABLE IF NOT EXISTS MON(
	MON_NO INT NOT NULL AUTO_INCREMENT,
	MA_MON VARCHAR(10) UNIQUE,
    TEN_MON NVARCHAR(50),
    NGAY_MO DATE,

    CONSTRAINT PK_MON PRIMARY KEY (MON_NO)
);

CREATE TABLE IF NOT EXISTS DANHSACHLOP_MON(
	DANHSACHLOP_NO INT NOT NULL AUTO_INCREMENT,
    MA_MON VARCHAR(10),
    MA_LOP NVARCHAR(8) NOT NULL UNIQUE,
	PHONG_HOC NVARCHAR(20),
    
    CONSTRAINT PK_DANHSACHLOP_MON PRIMARY KEY (DANHSACHLOP_NO),
    CONSTRAINT FK_DANHSACHLOP_MON FOREIGN KEY (MA_MON)
    REFERENCES MON(MA_MON),
    CONSTRAINT FK_DANHSACHLOP_MON_LOP FOREIGN KEY (MA_LOP)
    REFERENCES LOP(MA_LOP)
    
);

CREATE TABLE IF NOT EXISTS DANHSACHSINHVIEN_MON(
	DANHSACHSINHVIEN_NO INT NOT NULL AUTO_INCREMENT,
    MA_SINHVIEN VARCHAR(10) NOT NULL UNIQUE,
    
    MALOP_MON VARCHAR(20),
    MA_MON VARCHAR(10),
    
    CONSTRAINT PK_DANHSACHSINHVIEN_MON PRIMARY KEY(DANHSACHSINHVIEN_NO),
    CONSTRAINT FK_DANHSACHSINHVIEN_MON FOREIGN KEY (MA_MON)
    REFERENCES MON(MA_MON)
);

CREATE TABLE IF NOT EXISTS DIEM(
	MA_DIEM INT AUTO_INCREMENT,
    MA_MON VARCHAR(10),
    MA_SINHVIEN VARCHAR(10) NOT NULL,
    
    DIEM_GK FLOAT NOT NULL,
    DIEM_CK FLOAT NOT NULL,
    DIEM_KHAC FLOAT DEFAULT (0),
    
    CONSTRAINT PK_DIEM PRIMARY KEY (MA_DIEM),
    CONSTRAINT FK_DIEM_MON FOREIGN KEY (MA_MON)
    REFERENCES MON(MA_MON),
    CONSTRAINT FK_DIEM_SINHVIEN FOREIGN KEY (MA_SINHVIEN)
    REFERENCES SINHVIEN(MA_SINHVIEN)
);


-- Triggers
DROP TRIGGER IF EXISTS INSERT_SINHVIEN;
DELIMITER $$
CREATE TRIGGER INSERT_SINHVIEN
BEFORE INSERT ON SINHVIEN
FOR EACH ROW
BEGIN
	IF NEW.PASSWORD_SINHVIEN IS NULL 
		THEN
			BEGIN
				SET NEW.PASSWORD_SINHVIEN := NEW.CMND_SINHVIEN;
			END;
	END IF;
END$$
DELIMITER ;

DROP TRIGGER IF EXISTS INSERT_GIAOVU;
DELIMITER $$
CREATE TRIGGER INSERT_GIAOVU
BEFORE INSERT ON GIAOVU
FOR EACH ROW
BEGIN
	IF NEW.PASSWORD_GIAOVU IS NULL 
		THEN
			BEGIN
				SET NEW.PASSWORD_GIAOVU := 'giaovu';
			END;
	END IF;
END$$
DELIMITER ;

DROP TRIGGER IF EXISTS INSERT_DANHSACHLOP_MON;
DELIMITER $$
CREATE TRIGGER INSERT_DANHSACHLOP_MON
AFTER INSERT ON DANHSACHLOP_MON
FOR EACH ROW
BEGIN
		INSERT INTO DANHSACHSINHVIEN_MON (MA_SINHVIEN, MA_MON, MALOP_MON) 
        (SELECT MA_SINHVIEN, NEW.MA_MON, CONCAT(NEW.MA_LOP,NEW.MA_MON)
        FROM SINHVIEN WHERE MALOP_SINHVIEN = NEW.MA_LOP);
END$$
DELIMITER ;

-- INSERT DATABASE
INSERT INTO QUYEN VALUE (1,"ROLE_LECTURER","Giảng viên.");
INSERT INTO QUYEN VALUE (2,"ROLE_STUDENT","Sinh viên.");

INSERT INTO GIOITINH VALUE (1,"Nam");
INSERT INTO GIOITINH VALUE (2,"Nữ");

INSERT INTO LOP VALUE(NULL, "17CTT2", "CNTT2CQ", "Lớp 2 khoa CNTT ĐH KHTN TP HCM");

INSERT INTO SINHVIEN VALUE (NULL, 1712267, 1712267, "Nguyên Hoàng Thiên Ân", "025852371", "Nam","17CTT2",2);
INSERT INTO GIAOVU VALUE (NULL, 'giaovu', NULL, 'Trần Văn ABCXYZ', '1357902468','Nam',1);

INSERT INTO MON VALUE (NULL,"CTT011","Thiết kế giao diện",NOW());
INSERT INTO DANHSACHLOP_MON VALUE (NULL,"CTT011","17HCB","C32");


